<?php

namespace Civi\Repomanager\Features\Repository\Credential;

class CredentialFilter
{
    public ?string $idEquals = null;
    public mixed $idIn = null;
    public ?string $nameEquals = null;
    public mixed $nameIn = null;
    public ?string $nameLike = null;
    public ?string $passEquals = null;
    public mixed $passIn = null;
    public ?string $passLike = null;
    public ?string $untilEquals = null;
    public mixed $untilIn = null;
    public ?string $untilLike = null;
    public ?string $userEquals = null;
    public mixed $userIn = null;
    public ?string $userLike = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->idEquals = $data['idEquals'] ?? null;
        $self->idIn = $data['idIn'] ?? null;
        $self->nameEquals = $data['nameEquals'] ?? null;
        $self->nameLike = $data['nameLike'] ?? null;
        $self->nameIn = $data['nameIn'] ?? null;
        $self->userEquals = $data['userEquals'] ?? null;
        $self->userLike = $data['userLike'] ?? null;
        $self->userIn = $data['userIn'] ?? null;
        $self->passEquals = $data['passEquals'] ?? null;
        $self->passLike = $data['passLike'] ?? null;
        $self->passIn = $data['passIn'] ?? null;
        $self->untilEquals = $data['untilEquals'] ?? null;
        $self->untilLike = $data['untilLike'] ?? null;
        $self->untilIn = $data['untilIn'] ?? null;
        return $self;
    }
}