<?php

namespace Civi\Repomanager\Features\Repository\Package\Gateway;

use Civi\Repomanager\Features\Repository\Package\Package;
use Civi\Repomanager\Shared\Infrastructure\Store\EntityRepository;
use Civi\Repomanager\Shared\Infrastructure\Store\Repository;
class PackageGateway
{
    private readonly EntityRepository $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->entityRepository('repos', Package::class);
    }
    /**
     * @autogenerated
     */
    public function createPackage(Package $input)
    {
        $this->repository->create($input);
    }
    /**
     * @autogenerated
     */
    public function updatePackage(string $id, Package $input)
    {
        $this->repository->modify($id, $input);
    }
    /**
     * @autogenerated
     */
    public function removePackage(string $id)
    {
        $this->repository->delete($id);
    }
    /**
     * @autogenerated
     */
    public function listPackages(): array
    {
        return $this->repository->listView([], []);
    }
}