<?php

namespace Civi\SecurityStore\Features\Access\User;

class User
{
    public ?string $id = null;
    public ?string $name = null;
    public ?string $rol = null;
    public ?\DateTimeInterface $until = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->id = $data['id'] ?? null;
        $self->name = $data['name'] ?? null;
        $self->rol = $data['rol'] ?? null;
        $self->until = $data['until'] ?? null;
        return $self;
    }
}