<?php

namespace Civi\Repomanager\Features\Repository\Package\Schema;

use Civi\Repomanager\Features\Repository\Package\Package;
use Civi\Micro\Schema\TypeSchemaBuilder;
use Civi\Store\EntitySchemaBuilder;
use Civi\Store\Repository;

class PackageEntitySchemaBuilder
{
    private readonly EntitySchemaBuilder $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('repos', Package::class);
    }
    /**
     * @autogenerated
     */
    public function build(): TypeSchemaBuilder
    {
        return $this->repository->build();
    }
}