<?php

namespace Civi\Repomanager\Features\Repository\Credential\Gateway;

use Civi\Repomanager\Features\Repository\Credential\Credential;
use Civi\Repomanager\Shared\Infrastructure\Store\EntityRepository;
use Civi\Repomanager\Shared\Infrastructure\Store\Repository;
class CredentialGateway
{
    private readonly EntityRepository $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->entityRepository('repos', Credential::class);
    }
    /**
     * @autogenerated
     */
    public function createCredential(Credential $input)
    {
        $this->repository->create($input);
    }
    /**
     * @autogenerated
     */
    public function updateCredential(string $id, Credential $input)
    {
        $this->repository->modify($id, $input);
    }
    /**
     * @autogenerated
     */
    public function removeCredential(string $id)
    {
        $this->repository->delete($id);
    }
    /**
     * @autogenerated
     */
    public function listCredentials(): array
    {
        return $this->repository->listView([], []);
    }
}