<?php

namespace Civi\SecurityStore\Features\Access\User\Schema;

use Civi\SecurityStore\Features\Access\User\User;
use Civi\Micro\Schema\TypeSchemaBuilder;
use Civi\Store\EntitySchemaBuilder;
use Civi\Store\Repository;

class UserEntitySchemaBuilder
{
    private readonly EntitySchemaBuilder $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('usermanagement', User::class);
    }
    /**
     * @autogenerated
     */
    public function build(): TypeSchemaBuilder
    {
        $meta = $this->repository->build();
        return $meta;
    }
}
