<?php

namespace Civi\Repomanager\Features\Repository\Credential\View;

use Civi\Repomanager\Features\Repository\Credential\Credential;
use Civi\Repomanager\Shared\Infrastructure\View\ViewMetadata;
use Civi\Repomanager\Shared\Infrastructure\Store\EntityViewMetadata;
use Civi\Repomanager\Shared\Infrastructure\Store\Repository;
class CredentialViewMetadata
{
    private readonly EntityViewMetadata $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('repos', Credential::class);
    }
    /**
     * @autogenerated
     */
    public function build(): ViewMetadata
    {
        return $this->repository->build();
    }
}