<?php

namespace Civi\SecurityStore\Features\Access\User\View;

use Civi\SecurityStore\Features\Access\User\User;
use Civi\View\ViewMetadata;
use Civi\Store\EntityViewMetadata;
use Civi\Store\Repository;

class UserViewMetadata
{
    private readonly EntityViewMetadata $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('usermanagement', User::class);
    }
    /**
     * @autogenerated
     */
    public function build(): ViewMetadata
    {
        return $this->repository->build();
    }
}
