app:
  security:
    root: ruben.civeira@gmail.com
    routes:
      white-list:
        - /composer/repository
    oauth:
      redirect-host: http://localhost/dev/repo-manager/app/public
      redirect-path: /authorization
    oauth-providers:
      google:
        client-id: '%env(GOOGLE_CLIENT_ID)%'
        client-secret: '%env(GOOGLE_SECRET)%'
    authorized-users: '%env(USERS_ALLOWED)%'

