<?php

namespace Civi\Repomanager\Features\Repository\Package;

class Package
{
    public ?string $description = null;
    public ?string $id = null;
    public ?string $name = null;
    public ?string $status = null;
    public ?string $type = null;
    public ?string $url = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->id = $data['id'] ?? null;
        $self->name = $data['name'] ?? null;
        $self->url = $data['url'] ?? null;
        $self->type = $data['type'] ?? null;
        $self->status = $data['status'] ?? null;
        $self->description = $data['description'] ?? null;
        return $self;
    }
    public function withStatus(string $status): Package
    {
        $pack = clone $this;
        $pack->status = $status;
        return $pack;
    }
}