app:
  security:
    google:
      client-id: '%env(GOOGLE_CLIENT_ID)%'
      client-secret: '%env(GOOGLE_SECRET)%'
      redirect-uri: '%env(GOOGLE_REDIRECT_URL)%'
    authorized-users: '%env(USERS_ALLOWED)%'
    public-paths:
      - composer 

