<?php

declare (strict_types=1);
namespace Civi\Repomanager\Features\Repository\Package\Query;

class PackageFilter
{
    public ?string $descriptionEquals = null;
    public mixed $descriptionIn = null;
    public ?string $descriptionLike = null;
    public ?string $idEquals = null;
    public mixed $idIn = null;
    public ?string $nameEquals = null;
    public mixed $nameIn = null;
    public ?string $nameLike = null;
    public mixed $statusBetween = null;
    public ?string $statusEquals = null;
    public ?string $statusGreaterThan = null;
    public mixed $statusIn = null;
    public ?string $statusLessThan = null;
    public mixed $typeBetween = null;
    public ?string $typeEquals = null;
    public ?string $typeGreaterThan = null;
    public mixed $typeIn = null;
    public ?string $typeLessThan = null;
    public ?string $urlEquals = null;
    public mixed $urlIn = null;
    public ?string $urlLike = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->idEquals = $data['idEquals'] ?? null;
        $self->idIn = $data['idIn'] ?? null;
        $self->nameEquals = $data['nameEquals'] ?? null;
        $self->nameLike = $data['nameLike'] ?? null;
        $self->nameIn = $data['nameIn'] ?? null;
        $self->urlEquals = $data['urlEquals'] ?? null;
        $self->urlLike = $data['urlLike'] ?? null;
        $self->urlIn = $data['urlIn'] ?? null;
        $self->typeEquals = $data['typeEquals'] ?? null;
        $self->typeIn = $data['typeIn'] ?? null;
        $self->typeGreaterThan = $data['typeGreaterThan'] ?? null;
        $self->typeLessThan = $data['typeLessThan'] ?? null;
        $self->typeBetween = $data['typeBetween'] ?? null;
        $self->statusEquals = $data['statusEquals'] ?? null;
        $self->statusIn = $data['statusIn'] ?? null;
        $self->statusGreaterThan = $data['statusGreaterThan'] ?? null;
        $self->statusLessThan = $data['statusLessThan'] ?? null;
        $self->statusBetween = $data['statusBetween'] ?? null;
        $self->descriptionEquals = $data['descriptionEquals'] ?? null;
        $self->descriptionLike = $data['descriptionLike'] ?? null;
        $self->descriptionIn = $data['descriptionIn'] ?? null;
        return $self;
    }
}