<?php

namespace Civi\SecurityStore\Features\Access\User\Query;

class UserFilter
{
    public ?string $idEquals = null;
    public mixed $idIn = null;
    public ?string $nameEquals = null;
    public mixed $nameIn = null;
    public ?string $nameLike = null;
    public ?\DateTimeInterface $untilEquals = null;
    public ?\DateTimeInterface $untilIn = null;
    public ?\DateTimeInterface $untilLike = null;

    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->idEquals = $data['idEquals'] ?? null;
        $self->idIn = $data['idIn'] ?? null;
        $self->nameEquals = $data['nameEquals'] ?? null;
        $self->nameLike = $data['nameLike'] ?? null;
        $self->nameIn = $data['nameIn'] ?? null;
        $self->untilEquals = $data['untilEquals'] ?? null;
        $self->untilLike = $data['untilLike'] ?? null;
        $self->untilIn = $data['untilIn'] ?? null;
        return $self;
    }
}