<?php

namespace Civi\Repomanager\Features\Repository\Credential\Schema;

use Civi\Repomanager\Features\Repository\Credential\Credential;
use Civi\Micro\Schema\EntitySchema;
use Civi\Store\EntitySchemaBuilder;
use Civi\Store\Repository;
class CredentialEntitySchema
{
    private readonly EntitySchemaBuilder $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('repos', Credential::class);
    }
    /**
     * @autogenerated
     */
    public function build(): EntitySchema
    {
        return $this->repository->build();
    }
}