<?php

namespace Civi\SecurityStore\Features\Access\Rol\Query;

class RolFilter
{
    public ?string $idEquals = null;
    public mixed $idIn = null;
    public ?string $nameEquals = null;
    public mixed $nameIn = null;
    public ?string $nameLike = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->idEquals = $data['idEquals'] ?? null;
        $self->idIn = $data['idIn'] ?? null;
        $self->nameEquals = $data['nameEquals'] ?? null;
        $self->nameLike = $data['nameLike'] ?? null;
        $self->nameIn = $data['nameIn'] ?? null;
        return $self;
    }
}