<?php

namespace Civi\Repomanager\Features\Repository\Credential;

class Credential
{
    public ?string $id = null;
    public ?string $name = null;
    public ?string $pass = null;
    public ?string $until = null;
    public ?string $user = null;
    /**
     * @autogenerated
     */
    public static function from(array $data): self
    {
        $self = new self();
        $self->id = $data['id'] ?? null;
        $self->name = $data['name'] ?? null;
        $self->user = $data['user'] ?? null;
        $self->pass = $data['pass'] ?? null;
        $self->until = $data['until'] ?? null;
        return $self;
    }
}