<?php

namespace Civi\SecurityStore\Features\Access\User\Gateway;

use Civi\SecurityStore\Features\Access\User\User;
use Civi\Store\EntityRepository;
use Civi\Store\Repository;

class UserGateway
{
    private readonly EntityRepository $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->entityRepository('usermanagement', User::class);
    }
    /**
     * @autogenerated
     */
    public function createUser(User $input)
    {
        $this->repository->create('create', $input);
    }
    /**
     * @autogenerated
     */
    public function updateUser(string $id, User $input)
    {
        $this->repository->modify('update', $id, $input);
    }
    /**
     * @autogenerated
     */
    public function deleteUser(string $id)
    {
        $this->repository->change('delete', $id);
    }
    /**
     * @autogenerated
     */
    public function listUsers(array $query, array $include): array
    {
        return $this->repository->listView($query, $include);
    }
}
