<?php

namespace Civi\SecurityStore\Features\Access\Rol\Schema;

use Civi\SecurityStore\Features\Access\Rol\Rol;
use Civi\Micro\Schema\TypeSchemaBuilder;
use Civi\Store\EntitySchemaBuilder;
use Civi\Store\Repository;

class RolEntitySchemaBuilder
{
    private readonly EntitySchemaBuilder $repository;
    /**
     * @autogenerated
     */
    public function __construct(Repository $repository)
    {
        $this->repository = $repository->formMetadata('usermanagement', Rol::class);
    }
    /**
     * @autogenerated
     */
    public function build(): TypeSchemaBuilder
    {
        return $this->repository->build();
    }
}
